version: '3.1'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-banking-quarkus
    environment:
      POSTGRES_DB: banking-account-quarkus
      POSTGRES_USER: fabrice-root
      POSTGRES_PASSWORD: Bouhala12!
    ports:
      - "5432:5432"
    volumes:
      - postgresql:/var/lib/postgresql
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgresql:
  postgres_data: